{
    "name": "Meeting Room Booking",
    "author": "Jango",
    "version": "1.0",
    "category": "Services",
    "summary": "Meeting Room Booking Module",
    "depends": ["base", "mail"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/sequence.xml",
        "views/room_views.xml",
        "views/booking_views.xml",
        "views/menus.xml",
        "wizard/booking_wizard_views.xml",
    ],
    "installable": True,
    "application": True,
}
